# 钉钉配置
dingtalk:
  # 快仓智能科技有限公司appkey
  appKeyIntellect : dingdjzudqpvrqlucocs
  # 快仓智能科技有限公司appsecret
  appSecretIntellect: jsAmLunzCW0kUdt46fSEkS_cM9LEcad_kJpoBPdS2sJCa1jJd3ruKvB_KGrYsuZS

  # 快仓自动化科技有限公司key和secret
  appKeyAuto: dingmkjanvas6bnh3pj8
  appSecretAuto: fdrqrBtY38twoO_OHqrTr4kWbQBLHDlXPnjzdgfCM-nOqvMMD06j5ur7fGfEceKp

